# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kalenitid/CLionProjects/Logistics-Management-System

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kalenitid/CLionProjects/Logistics-Management-System

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kalenitid/CLionProjects/Logistics-Management-System/CMakeFiles /Users/kalenitid/CLionProjects/Logistics-Management-System//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kalenitid/CLionProjects/Logistics-Management-System/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named logistics_management_system

# Build rule for target.
logistics_management_system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logistics_management_system
.PHONY : logistics_management_system

# fast build rule for target.
logistics_management_system/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logistics_management_system.dir/build.make CMakeFiles/logistics_management_system.dir/build
.PHONY : logistics_management_system/fast

item.o: item.c.o
.PHONY : item.o

# target to build an object file
item.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logistics_management_system.dir/build.make CMakeFiles/logistics_management_system.dir/item.c.o
.PHONY : item.c.o

item.i: item.c.i
.PHONY : item.i

# target to preprocess a source file
item.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logistics_management_system.dir/build.make CMakeFiles/logistics_management_system.dir/item.c.i
.PHONY : item.c.i

item.s: item.c.s
.PHONY : item.s

# target to generate assembly for a file
item.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logistics_management_system.dir/build.make CMakeFiles/logistics_management_system.dir/item.c.s
.PHONY : item.c.s

repository.o: repository.c.o
.PHONY : repository.o

# target to build an object file
repository.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logistics_management_system.dir/build.make CMakeFiles/logistics_management_system.dir/repository.c.o
.PHONY : repository.c.o

repository.i: repository.c.i
.PHONY : repository.i

# target to preprocess a source file
repository.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logistics_management_system.dir/build.make CMakeFiles/logistics_management_system.dir/repository.c.i
.PHONY : repository.c.i

repository.s: repository.c.s
.PHONY : repository.s

# target to generate assembly for a file
repository.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logistics_management_system.dir/build.make CMakeFiles/logistics_management_system.dir/repository.c.s
.PHONY : repository.c.s

server.o: server.c.o
.PHONY : server.o

# target to build an object file
server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logistics_management_system.dir/build.make CMakeFiles/logistics_management_system.dir/server.c.o
.PHONY : server.c.o

server.i: server.c.i
.PHONY : server.i

# target to preprocess a source file
server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logistics_management_system.dir/build.make CMakeFiles/logistics_management_system.dir/server.c.i
.PHONY : server.c.i

server.s: server.c.s
.PHONY : server.s

# target to generate assembly for a file
server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logistics_management_system.dir/build.make CMakeFiles/logistics_management_system.dir/server.c.s
.PHONY : server.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... logistics_management_system"
	@echo "... item.o"
	@echo "... item.i"
	@echo "... item.s"
	@echo "... repository.o"
	@echo "... repository.i"
	@echo "... repository.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

